package com.chicu.neurotradebot.session;

public enum InputStage {
    NONE,
    ENTER_API_KEY,
    ENTER_SECRET_KEY,
    AI_LIST_ADD,
    AI_STRATEGY_MENU,
    AI_STRATEGY_SET_RSI_PERIOD,
    AI_STRATEGY_SET_EMA_SHORT,
    AI_STRATEGY_SET_EMA_LONG,
    AI_STRATEGY_SET_RSI_BUY,
    AI_STRATEGY_SET_RSI_SELL,
    AI_STRATEGY_SET_LIMIT

}
